#+title: Episteme

Apoptosis' community knowledge-base built ontop a customized Emacs.

The knowledge-base is comprised of [[./org][organized files]], written in [[https://orgmode.org/][Org-mode.]]

* Installing

You must have the following globally available:

- Emacs
- Git

Start by cloning Episteme somewhere:

#+begin_src sh
  git clone https://github.com/apoptosis/episteme.git ~/episteme
#+end_src

** Linux

Just run =episteme=:

#+begin_src sh
  ./episteme -h
#+end_src

** NixOS

Install =episteme=:

#+begin_src sh
  nix-env -i -f .
#+end_src

Then run:

#+begin_src sh
  episteme -h
#+end_src

*** Epi helper

A small helper =epi= is provided to bake in the =-repo= flag.

Edit =epi.nix= to adjust the =-repo= flag to point to the Episteme repo on your
machine. Then install it:

#+begin_src sh
  nix-env -i -f epi.nix
#+end_src

** TODO Windows

???

* Running Episteme

Use the =-h= flag to explore the =episteme= cli:

#+begin_src
  episteme [EPISTEME-OPTS] [EMACS-OPTS]

    EPISTEME-OPTS:
      -h             list usage
      -repo          Episteme repo (default: $PWD)
      -themes        print theme names & exit
      -theme NAME    use theme called NAME

    EMACS-OPTS:
      typical Emacs options
#+end_src

** -repo

Use this to specify the location of the Episteme git repo.

If you run =episteme= from inside the repo, this flag is not necessary.

** -config

Use this to specify the location of the Episteme config directory.

This is the directory where =config.el= should be placed.

The default is =$HOME/.config/episteme=

** -themes

List the available themes.

** -theme

Specify the name of theme to use.

** Emacs Options

Any additional options will be passed to emacs.

* Configuration

Edit =config.el= within the Episteme configuration directory to customize
options.

** Setting options

Options are set with the =setq= function:

#+begin_src emacs-lisp
  (setq variable-name "variable value")
#+end_src

** Keybindings

#+begin_src emacs-lisp
  ;; keybind for the main menu
  (setq episteme/main-menu-key "C-c x")

  ;; keybind for the mode menu
  (setq episteme/mode-menu-key "C-c m")
#+end_src

** Additional Configuration

Your =config.el= may contain any additional emacs configuration.

* Main Menu

Activate the main menu with the keybind assigned to =episteme/main-menu-key= (=C-c
x= by default).

The spacebar will return to previous menus.

The main menu offers a few options for navigating Episteme:

** =o=: open
Walk directories and files until reaching the desired content.

Use =enter= to navigate.

Use =C-enter= to visit the currently selected item.

** =g=: github

Open the git interface.

As you make changes to Episteme you'll use git to submit your changes.

** =h=: help

Access a comprehensive menu.

** =m=: mark

Manipulate the document mark.

** =w=: windows

Manage the emacs windows.

** =z=: zoom

Adjust the zoom per-buffer or globally.

** =r=: registers

Maniplate the emacs registers.

** =;=: embrace

Convert between balanced parenthesis types. (e.g. (foo) => [foo], etc.)

* Mode Menus

Activate the mode menu for the current buffer mode, if there is one, with the
keybind assigned to =episteme/mode-menu-key= (=C-c m= by default).

The spacebar will return to previous menus.

Modes which currently feature a menu:

- =emacs-lisp-mode=
- =org-mode=

Each mode menu is different, so explore!
