#+title: IRC

* Help
** Didn't get confirm email
/alias add help-email /msg * $1: Try /ns resend
** Channel transfer
/alias add help-founder /msg * $1: /join #chanhelp
** Namespace rule
/alias add help-pound /msg * $1: The #/## namespace rule is no longer policy.

* Moderation
** Service aliases
/alias add os /quote os $*
/alias add cs /msg chanserv $*
/alias add ns /msg nickserv $*
** Akill
/alias add akill /quote os akill add +3d $*

** Hostmasks
Format: =nick!user@host=
  - *nick*: user selected nickname
  - *user*: ident reported username / ~ prefixed nick (if no ident)
  - *host*: ip or reverse dns name
** User Control
*** Kicking
=/kick <channel> <nick> <reason>=
*** Auto-kick
If the =!P= token is specified, the AKICK will never expire (permanent). If the
=!T= token is specified, expire time must follow, in minutes, hours ("h"), days
("d") or weeks ("w").

/msg chanserv AKICK #foo ADD bar you are annoying | private op info
/msg chanserv AKICK #foo ADD *!*foo@bar.com !T 5d
/msg chanserv AKICK #foo DEL bar
/msg chanserv AKICK #foo LIST
*** Banning
=/ban <channel> <nick/mask>=
*** K-line

** User Permissions
*** Operators

** Channel Modes
set a mode with:
    =/mode #channel +/-attribute [data]=

| flag        | description                                                                          |
|-------------+--------------------------------------------------------------------------------------|
| +n          | Disallows external messages.                                                         |
| +t          | Only op/hops can set the topic.                                                      |
| +p          | Sets the channel as invisible in /list.                                              |
| +s          | Sets the channel as invisible in /list and /whois.                                   |
| +i          | Sets the channel as closed unless the person was invited.                            |
| +k [pass]   | Sets a password for the channel which users must enter to join.                      |
| +l [number] | Sets a limit on the number of users who are allowed in the channel at the same time. |
| +m          | Prevents users who are not opped/hopped/voiced from talking.                         |
| +R          | Sets the channel so only registered nicks are allowed in.                            |
| +M          | Sets the channel so only registered nicks are allowed to talk.                       |
| +S          | Strips formatting from messages, rendering them as plaintext.                        |
| +c          | Blocks messages containing color codes.                                              |
| +i          | A user must be invited to join the channel.                                          |
| +N          | No nick changes permitted in the channel.                                            |

** ChanServ

All ChanServ commands begin with =/cs= or =/chanserv= or =/msg ChanServ=. Depending
on your client and network, =/cs= or =/chanserv= may not work. I will use the
shorthand in these examples.

| command                                    | description                                                                               |
|--------------------------------------------+-------------------------------------------------------------------------------------------|
| /cs identify #channel <password>           | Identifies you as the channel's founder and gives you founder-level privileges.           |
| /cs register #channel password description | Registers the current channel to you with ChanServ and sets its password and description. |
| /cs drop #channel [dropcode]               | Un-registers the current channel to you with ChanServ.                                    |

** Control Flags
Use =/cs set #channel <flag> <args>= to set Control Flags
| mlock modes               | Locks the channel's modes. Just + unlocks all.                                            |
| secureops [on:off]        | Keeps everyone except aops, sops, and the founder from becoming ops.                      |
| keeptopic [on:off]        | Maintains the topic even if everyone leaves.                                              |
| enforce [on:off]          | Restores op/halfop/voice if a person with op/halfop/voice gets de-opped/halfopped/voiced. |
| leaveops [on:off]         | Whether or not to allow the first person who join the channel to get ops.                 |
| founder [nickname]        | Sets the current channel's founder.                                                       |
| password [newpass]        | Changes the current channel's password to newpass.                                        |
| desc [description]        | Changes the current channel's description.                                                |
| url [address]             | Associates a URL with the channel.                                                        |
| email [email@address]     | Associates an email address with the channel.                                             |

* User Settings

** Hide joined channels from /whois

* Feedback

** Jinx - Wants policy clarification on "advertising"

2021-06-10 17:46:37	--	Msg:@(Jinx): So I see the "no advertising other networks" bit has been dropped from the topic--but is it still policy?
2021-06-10 17:48:03	@ldlework	Jinx: https://freenode.net/policies
2021-06-10 17:50:08	--	Msg:@(Jinx): Would you care to point me to the relevant section? I don't see anything that specifically addresses this concern.
2021-06-10 17:52:37	--	Msg:@(Jinx): As someone who's been coming here for about 15 years, I'm familiar with the "On-topic"/"Off-topic" policy, but surely recent history has suggested this alone does not clarify the situation sufficiently. It seems like if there was no specific guidance on this before, there should be now. Since #freenode-policy-feedback redirects here, I assume this is where you'd like to hear such feedback. :)
2021-06-10 17:58:05	@ldlework	Jinx: It is. In my judgement, the first two paragraphs under the Off-topic section is most relevant. That said, I noted your comment.
2021-06-10 18:00:18	--	Msg:@(Jinx): "It is."? Meaning "no advertisign other networks" is still policy?
2021-06-10 18:01:22	@ldlework	Jinx: That you're welcome to give feedback in this channel, sorry :)
2021-06-10 18:01:37	--	Msg:@(Jinx): Ah... thanks for clarifying.
2021-06-10 18:02:56	--	Msg:@(Jinx): I've read those 2 paragraphs repeatedly, and I'm not seeing how the apply. All I can assume is you are referring to "inappropriate advertising"--which is certainly not specific. If "no advertising other networks" (e.g. in channel topics / "other forms") is still policy, I'd like to suggest it have a more specific section/statement.
2021-06-10 18:03:06	--	Msg:@(Jinx): s/how the/how they
2021-06-10 18:03:44	 *	Jinx still can't figure out if it is policy or not :)
2021-06-10 18:06:07	@taw	Jinx: I think it's open to interpretation. It's factual that some channels have decided to move, and have pointed that out to their users. However, actively messaging people, closing channels, silencing communities in order to make people leave freenode is not okay.
2021-06-10 18:06:30	@taw	We believe in freedom, and that includes freedom of choice.
2021-06-10 18:09:35	--	Msg:@(Jinx): I understand that perspective and appreciate you explaining it. I'm not here to litigate (I'm sure you've had enough drama), but I have to admit the stories I've heard have been concerning to say the least. So, I think it'd be in everyone's best interest to explain in more detail in the policies just under what circumstances a channel can "move" or not.
2021-06-10 18:09:56	--	Msg:@(Jinx): I hope this is something that can be discussed for consensus at the next staff meeting :)
2021-06-10 18:12:25	@taw	Jinx: absolutely. I agree with you there. There are lot of things we have on our plate, and while we can't make everyone happy, one thing we can do is push forward and power through, and come up with new tools and services we can provide our community.
2021-06-10 18:12:39	--	Msg:@(Jinx): My personal proposal would be some sort of "transition period" in which the existing owners have 30-days to inform their users of such a move before other "representatives" can claim it.
2021-06-10 18:13:14	@taw	I need to drop for a bit, but it's an interesting perspective.
2021-06-10 18:13:18	@taw	ttyl
2021-06-10 18:13:27	--	Msg:@(Jinx): alright, thank you for your time, taw

*** whois
#+begin_src text
  17:59 -- [Jinx] (~Jinx@unaffiliated/jinx): Jinx Dojo
  17:59 -- [Jinx] #freenode
  17:59 -- [Jinx] kornbluth.freenode.net (Frankfurt, Germany)
  17:59 -- [Jinx] is using a secure connection
  17:59 -- [Jinx] is logged in as Jinx
  17:59 -- [Jinx] End of /WHOIS list.
#+end_src
