#+title: Biology

* Molecular Biology
** Amino Acids
https://youtu.be/Pk4d9lY48GI

Amino Acids are molecules with a standard inner structure, allowing them to be
repeatedly linked together into "peptide chains". Each amino acid is
differentiated by a molecular side-chain structure unique to each amino
acid. What is this standard structure and how do the side-chains fit into the
picture?

As a peptide chain, or polypeptide, forms various forces, dependant on the
specific amino acids in the peptide, and their ordering, cause the peptide to
fold into a specific structure. The folded structure is called a protein. What
are these various forces and how do they fold the peptide into a protein?

https://courses.lumenlearning.com/boundless-chemistry/chapter/protein-structure/

How does DNA and RNA are linear molecular chains (much like peptides) but
composed of just 4 unique molecules called nucleotides. But there are over 60
amino acids which can partake in polypeptides. How is DNA robust enough to
encode for so many amino acids? Further, how are polypeptides, which fold into
proteins, actually manufactured using genetic information?

https://www.youtube.com/watch?v=7EZ87bIvCOM

A common mis-conceptualization of how biological materials reach their
destinations are through osmosis, diffusion and other random brownian
motions. However, there is a whole domain of motor proteins which can actually
walk along the microtubule cytoskeleton and actin filiments of a cell and drag
along specially targetted cargo. How many kinds of motors are there? What are
their exact mechanisms of action? What roles in cell function and health do
motor proteins serve?

https://www.youtube.com/watch?v=9RUHJhskW00



