#+TITLE:Economics

* Austrian School
** Praxeology
Praxeology is the study of human action, it provides a framework for understanding the purposeful behaviour of man. Any praxeological argument with sound logic and accepted axioms is necessarily true.

#+begin_quote
Praxeology represents an attempt to escape the nihilistic implications of both historicism and empiricism. It affirms the operation of inviolable laws within the realm of human action.
#+end_quote
 --- Quoted from George A. Selgin, "Praxeology and Understanding: An Analysis of the Controversy in Austrian Economics", /Ludwig von Mises Institute/, p. 14

Praxeology stands opposed to mainstream economic modelling in that it relies entirely on logical derivations from axioms to construct economic /theories/, not simply economic models. Moreover these theories may only be contested by discovery of a fault in ones line of reasoning, not by looking to historical examples --- a praxeological argument can only be countered with another praxeological argument.

Praxeology relies on the assumption that humans act purposefully, which is [[the Axiom of Action]]. It implies the notion that value, wealth, profit, loss, and costs are all products of human thought, having no objective foundation --- one cannot imagine their existence or conceive their alteration outside of a connection with acts of subjective valuation and choice.

Sense data alone, moreover, could not reveal to us the essential purposefulness of human actions, empirical evidence may only serve to establish the appropriateness of a theory's application to a particular event.

Praxeology is distinct from psychology in that it simply wishes to describe subjective valuations and choices not to uncover the underlying motivations, thoughts, or ends from which they rose. Moreover, praxeological theories, as understood by Mises, are independent of the particular psychological makeup of individual --- praxeology does not address the /content/ of individual preferences or the particular motives that gide rise to those preferences, it is solely concerned with the pure /logic/ of choice. In other words, it is [[Value-Free][value-free]].

*** Purposeful Behaviour
The [[the Axiom of Action][Action Axiom]], "human action is purposeful behaviour," describes mans conscious aiming at ends and selection of means to achieve those ends. This is distinct to unconscious behaviour such as involuntary reflexes.

Reflexes or situations outside of a mans control, such as an illness or the weather, are all facts that a man must take into account when acting. There are situations when a man can succeed through the power of his will in overcoming sickness, or he can compensate for physical inefficiencies, or he can train himself to suppress reflexes. As far as this is possible the field of purposeful behaviour is extended, and thus praxeology may be used in analysis.

When praxeology speaks of action, it does not just speak of having preference, but actually /showing/ preference. There are situations where a man has preference for things outside of his control --- Crusoe may well prefer it to be sunny than rainy, but he cannot /choose/ for it to be sunny, and thus he does not /show/ this preference. The acting man specifically chooses means to reach an end that he values more than his current situation --- if there are two things that a man cannot have at the same time he must select one and give up the other, /showing/ a preference, moreover this means that action involves taking and renunciation at the same time.

Praxeology doesn't distinguish between active or passive action --- there's no difference between a cook who shows up to work every day and an unemployed college graduate who chooses to stay home instead of looking for work. If you have the ability to change the future, and are aware of this ability, it does not matter whether you choose to do something or not, you show a preference either way and therefore act either way.

*** Prerequisites of Action
A man acts when he is eager to resolve some state of uneasiness --- his environment is in some unsatisfactory state, and he wishes to substitute this for a more satisfactory state. His mind imagines conditions that could suit him better and his action aims at bringing about these desired conditions. Moreover, if and only if a man believes his action could bring about a better state of affairs can he act.

Here we have defined the three prerequisites of action:
1. A state of uneasiness.
2. An imagined world without this uneasiness.
3. The belief that a proposed action will bring about this imagined world.

Without all three of these you cannot have purposeful behaviour, and thus you cannot have action.

For example if you remove the state of uneasiness you destroy mans incentive to act, and you make a choice between this uneasy state and a better state impossible. You are no longer talking about a real man, but a perfectly content individual who never wants for anything, and has no reason to change his situation.

If you remove the imagination of a world without this uneasiness, man has no ability to substitute it for his uneasy world, as it does not exist in his mind. Moreover without the ability to imagine a changed world man has no ability to imagine actions that may bring about the desired change, so no action is possible --- every man would simply be submitting himself to the whims of destiny in such a world.

*** The Rationality of Action
Action is always necessarily rational, as an acting man is always aiming his action to satisfy some desire. The terms rational and irrational are meaningless with respect to the subjective goals of a man.

Suppose that Steve has to decide whether to go to a park or to a Beatles concert, and he chooses to go to the park. Peter calls Steve's decision irrational, but this cannot be true as what Steve values is up to him alone. The only thing Peter claims to know here is what he would have done in the same situation.

Now let's imagine that Steve actually wanted to go to the Beatles concert but someone told him that it would be held in the park, when it actually wasn't, can Peter now call Steve's decision irrational? Steve went to the wrong location, but he was acting on the information available to him --- he did his best. Moreover, just because a man fails to achieve his end does not mean that the means he employed were irrational --- since no one is in a position to substitute their own values for those of another it is futile to pass judgements on the values of an acting man, the only place where a praxeologist may pass judgement is on whether the means chosen are fit for achieving the desired end.

*** Ends and Means
When man acts the result he wishes to achieve can be called his end, his goal, or his aim --- these terms are interchangeable in praxeology. When man acts he always seeks to remove some uneasiness and his end is the desired state without this uneasiness.

For a man to achieve his desired end he must employ a means. A thing becomes a means when human reason plans to employ it for the attainment of some end and human action is what actually employs it for this purpose.

It's important to note that neither ends nor means exist in the physical universe without man --- in the universe there are no means, there are merely things, man is required to give these things meaning. When praxeology speaks of ends and means it is referring to the conscious meaning man gives to the world around him. If he has a goal he wishes to achieve it is because his mind percieves some uneasiness but this may not be empirically observed by other people and praxeology never refers to it as such.

A goal starts as an idea a man holds internally and becomes a real goal when he acts to achieve it. Likewise, things first have to be identified in the mind of man as serviceable --- man has to apply a meaning to a thing that he thinks can achieve his goal. These things become means when an acting man actually employs them in an attempt to reach some end.

*** TODO Scale of Values

** TODO Economic Calculation
/See: [[https://mises.org/library/how-do-we-calculate-value][Ludwig von Mises, "Socialism: An Economic and Sociological Analysis," pp. 113-122]] for more information/

Human action is the exchange of one condition for another.
** Ordinal vs Cardinal Value
Ordinal values are values that are ranked, whereas cardinal values have specific quantities, or /cardinalities/. For example the positions people come in a 100m dash do not correlate to the time they took, but merely the order that they passed the finish line in. Conversely the time any individual took to finish the race is a cardinal value --- the times of others has no bearing on it.

In the realm of economics, many schools adopt a cardinal view of value where an apple has 10 utils of value, a banana has 6, and a pear has 3. And from this the classical economist would say that apples are more valuable than the other fruits and further that, apples will trade at 10 utils of currency.

Carl Menger pointed out that this is a flawed view and proposed an ordinal and subjective theory of value, where individual A might have the following value scale:
1. Apple
2. Banana
3. Pear

And B might have:
1. Banana
2. Apple
3. Pear

He then makes the further observation that A would be willing to trade for an apple with B and B would accept this trade if given a Banana in return by A, as they both value the other guys item more and therefore both profit. This is the austrian observation of [[Mutual Profit][necessary ex ante mutual profit in trade]].
** Mutual Profit
In the Austrian school, contra more mainstream schools, it is recognised that /both/ parties to a voluntary trade profit --- classical economics says that both break even and Marxian economics says that one is exploited. But this cannot be the case. If either A or B did not value the other parties item they would not agree to make the trade, so by making the trade we know, [[A Priori][a priori]], that both A and B profit.

As a demonstration, say that John is buying a hotdog from a hotdog vendor for $5. From this we know that, for some reason, John values the hotdog more than the $5, and conversely that the hotdog vendor values the $5 more than the hotdog. In this example they both end up with the more valuable item, they both profit.
** TODO Marginal Utility
Carl Menger pointed out that utility can be best thought of as ones subjective satisfaction, it is the result of an individuals [[Ordinal vs Cardinal Value][ordinal]] judgement, this ran counter to the economists of Menger's age, who saw utility as cardinal.

** TODO A Priori
/A priori/, to Mises, means "independent of any particular time or place." It does not imply independence from all experience, although it does denote independence from the sort of sensory experience that empiricism and positivism emphasize:
#+begin_quote
It rests on universal inner experience, and not simply on external experience, i.e., its evidence is reflective rather than physical.[fn:1]
#+end_quote
** TODO Axiom
** TODO Postulate
** TODO Value-Free
Value-free, aka /wertfrei/, is one of the most basic notions of Austrian economics, taken from Max Weber by Mises.

** Axioms
*** the Axiom of Action
This is the axiom that man acts [[Purposeful Behaviour][purposefully]]. This axiom is not merely analytic (i.e. non-empirical or vacuous), it is based upon the reality of the pursuit of ends and the choice of means for their attainment that distinguishes all mental (and, hence, human) activity.[fn:2]

Meaningfully denying this axiom is difficult, denial of the axioms empirical validity involves a purposeful act on the sceptics part. It therefore confronts them with the uncomfortable choice of either ceding the issue or proclaiming that their own disagreement is purposeless.

Yet this axiom is neither empty nor arbitrary (see: [[A Priori]]), it is axiomatic in the sense that it distinguishes an /[[Axiom][axiom]]/ from a /[[Postulate][postulate]]/. It is epistemologically distinct from the [[A Priori][a priori]] assumptions employed in the hypothetical-deductive procedures of orthodox, neoclassical economics.[fn:3]
* Classical School
** What it Gets Right
The Classical School of Economics agrees with [[Austrian School][austrianism]] in a few key areas:
+ The Classical School is correct that prices are not random, they are formed by immutable laws --- I cannot just choose to sell a pear at an arbitrarily high sum.
+ The Classical School is correct that prices are used by business to calculate profits and losses, and thus there is this idea of prices being cummunicative of some information.
+ The Classical School is correct that profits encourage business to increase supply and losses drive the reduction of supply.
+ The Classical School is also correct that in the long run, cetirus paribus, you would expect profits and losses to tend to 0, this is a process that austrians call equilibration.

** What it Gets Wrong
The big flaw of Classical economics was that it sees goods only in terms of classes of goods, i.e. is 'steel' more important than 'diamonds,' are 'diamonds' more important than 'water,' etc. But it fails to acknowledge that humans do not think in these terms, people think about, "should I buy 1 gallon of milk," or "shall I buy 3 gallons of water," etc. These are /marginal/ units.

This failure to understand how consumers value goods leads to the famous diamond-water paradox, solved by Menger's [[Marginal Utility][theory of marginal utility]]. The Classical school is unable to resolve this paradox, because they split value into two parts, exchange value, and use value, and they said economics is concerned only with exchange value which they define as the costs incurred by the businessman in production, known as the "Cost of Production Theory of Value."

But this theory fails to account for the paradox -- even when ignoring the use value, which they peg as massively high for water due to their lack of a theory of falling marginal utility -- as diamonds can often be vastly cheaper to produce than they sell for. The Classical economists then say that expensive, one of a kind, diamonds have a monopoly value, which begs the question of how that could occur if exchange value is determined by the costs of production --- much like the Marxian "socially necessary" clause in the LTV it seems like an attempt to sneak subjective value past the gates. Moreover this theory fails to account for why any business should ever lose money, as they would simply raise prices to account for costs.

* References
+ George A. Selgin, "Praxeology and Understanding: An Analysis of the Controversy in Austrian Economics, /Ludwig von Mises Institute/, p. 14
+ [[https://www.youtube.com/playlist?list=PLEE9A33593A261433][Praxgirl, "Praxeology 101"]]

* Footnotes

[fn:1]Murray N. Rothbard, "In Defense of 'Extreme Apriorism'," /Southern Economic Journal/ 23, no. 3 (January 1957): 314-20.

[fn:2]William James, The Principles of Psychology (New York: Dover, 1950), p.8.

[fn:3]Contra John B. Egger. See "The Austrian Method," in /New Directions in Austrian Economics/, Louis M. Spadaro, ed. (Kansas City, Kans.: Sheed Andrews and McMeel, 1978), p. 20.
