#+title: western philosophy
#+description: Philosophy knowledge-base of the ##apoptosis community on Freenode
#+language: en
#+startup: overview indent align
#+babel: :cache no
#+options: ^:nil num:nil tags:nil
#+html_head: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+html_head: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
#+html_head: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+html_head: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+html_head: <script type="text/javascript" src="https://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+html_head: <script type="text/javascript" src="https://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>
#+html_head: <link rel="stylesheet" type="text/css" href="/episteme/extra.css"/>

* Resources
** Interesting SEP Articles
Chance versus Randomness https://plato.stanford.edu/entries/chance-randomness/
Temporal Consciousness https://plato.stanford.edu/entries/consciousness-temporal/
Seventeenth-Century Theories of Consciousness https://plato.stanford.edu/entries/consciousness-17th/
Adaptationism https://plato.stanford.edu/entries/adaptationism/
Computation in Physical Systems https://plato.stanford.edu/entries/computation-physicalsystems/
Faith https://plato.stanford.edu/entries/faith/
The Ethics of Belief https://plato.stanford.edu/entries/ethics-belief/
Ayn Rand https://plato.stanford.edu/entries/ayn-rand/
Immanuel Kant https://plato.stanford.edu/entries/kant/
Theory and Bioethics https://plato.stanford.edu/entries/theory-bioethics/
Immigration https://plato.stanford.edu/entries/immigration/
Forgiveness https://plato.stanford.edu/entries/forgiveness/
Political Legitimacy https://plato.stanford.edu/entries/legitimacy/
Free Logic https://plato.stanford.edu/entries/logic-free/
Truth Values https://plato.stanford.edu/entries/truth-values/
Causal Theories of Mental Content https://plato.stanford.edu/entries/content-causal/
Introspection https://plato.stanford.edu/entries/introspection/
Omniscience https://plato.stanford.edu/entries/omniscience/
Theories of Meaning https://plato.stanford.edu/entries/meaning/
Abilities https://plato.stanford.edu/entries/abilities/
Desire https://plato.stanford.edu/entries/desire/
Impossible Worlds https://plato.stanford.edu/entries/impossible-worlds/
Delusion https://plato.stanford.edu/entries/delusion/
Information Processing and Thermodynamic Entropy https://plato.stanford.edu/entries/information-entropy/
The Concept of the Aesthetic https://plato.stanford.edu/entries/aesthetic-concept/
Attention https://plato.stanford.edu/entries/attention/
Intention https://plato.stanford.edu/entries/intention/
Kant's Transcendental Arguments https://plato.stanford.edu/entries/kant-transcendental/
Underdetermination of Scientific Theory https://plato.stanford.edu/entries/scientific-underdetermination/
The Distinction Between Innate and Acquired Characteristics https://plato.stanford.edu/entries/innate-acquired/
Locke's Philosophy of Science https://plato.stanford.edu/entries/locke-philosophy-science/
Platonism in the Philosophy of Mathematics https://plato.stanford.edu/entries/platonism-mathematics/
The Disjunctive Theory of Perception https://plato.stanford.edu/entries/perception-disjunctive/
The Normativity of Meaning and Content https://plato.stanford.edu/entries/meaning-normativity/
Patriotism https://plato.stanford.edu/entries/patriotism/
Modularity of Mind https://plato.stanford.edu/entries/modularity-mind/
The Logic of Action https://plato.stanford.edu/entries/logic-action/
The History of Utilitarianism https://plato.stanford.edu/entries/utilitarianism-history/
Reid on Memory and Personal Identity https://plato.stanford.edu/entries/reid-memory-identity/
Thomas Hobbes https://plato.stanford.edu/entries/hobbes/
Scientific Revolutions https://plato.stanford.edu/entries/scientific-revolutions/
Dialogical Logic https://plato.stanford.edu/entries/logic-dialogical/
The Incommensurability of Scientific Theories https://plato.stanford.edu/entries/incommensurability/
Material Constitution https://plato.stanford.edu/entries/material-constitution/
Reasons for Action: Justification, Motivation, Explanation https://plato.stanford.edu/entries/reasons-just-vs-expl/
Spinoza's Theory of Attributes https://plato.stanford.edu/entries/spinoza-attributes/
The Ethics of Clinical Research https://plato.stanford.edu/entries/clinical-research/
Transitional Justice https://plato.stanford.edu/entries/justice-transitional/
Skolem's Paradox https://plato.stanford.edu/entries/paradox-skolem/
Theory and Observation in Science https://plato.stanford.edu/entries/science-theory-observation/
Epictetus https://plato.stanford.edu/entries/epictetus/
Morality and Evolutionary Biology https://plato.stanford.edu/entries/morality-biology/
Rene Descartes https://plato.stanford.edu/entries/descartes/
Combinatory Logic https://plato.stanford.edu/entries/logic-combinatory/
Causal Decision Theory https://plato.stanford.edu/entries/decision-causal/
Formal Representations of Belief https://plato.stanford.edu/entries/formal-belief/
Occasionalism https://plato.stanford.edu/entries/occasionalism/
Promises https://plato.stanford.edu/entries/promises/
Constructive Empiricism https://plato.stanford.edu/entries/constructive-empiricism/
Aristotle https://plato.stanford.edu/entries/aristotle/
Natural Kinds https://plato.stanford.edu/entries/natural-kinds/
Names https://plato.stanford.edu/entries/names/
Kant's Account of Reason https://plato.stanford.edu/entries/kant-reason/
Pragmatism https://plato.stanford.edu/entries/pragmatism/
Chaos https://plato.stanford.edu/entries/chaos/
Self-Reference https://plato.stanford.edu/entries/self-reference/
Natural Selection https://plato.stanford.edu/entries/natural-selection/
Kant and Hume on Causality https://plato.stanford.edu/entries/kant-hume-causality/
Race https://plato.stanford.edu/entries/race/
Weakness of Will https://plato.stanford.edu/entries/weakness-will/
Essential vs. Accidental Properties https://plato.stanford.edu/entries/essential-accidental/
Definitions https://plato.stanford.edu/entries/definitions/
Empathy https://plato.stanford.edu/entries/empathy/
Kant and Hume on Morality https://plato.stanford.edu/entries/kant-hume-morality/
Evolutionary Psychology https://plato.stanford.edu/entries/evolutionary-psychology/
Value Theory https://plato.stanford.edu/entries/value-theory/
Certainty https://plato.stanford.edu/entries/certainty/
Innateness and Language https://plato.stanford.edu/entries/innateness-language/
Decision-Making Capacity https://plato.stanford.edu/entries/decision-capacity/
Zeno of Elea https://plato.stanford.edu/entries/zeno-elea/
The Axiom of Choice https://plato.stanford.edu/entries/axiom-choice/
Animal Cognition https://plato.stanford.edu/entries/cognition-animal/
Civic Education https://plato.stanford.edu/entries/civic-education/
Second-order and Higher-order Logic https://plato.stanford.edu/entries/logic-higher-order/
A Priori Justification and Knowledge https://plato.stanford.edu/entries/apriori/
Deontological Ethics https://plato.stanford.edu/entries/ethics-deontological/
Structural Realism https://plato.stanford.edu/entries/structural-realism/
Seneca https://plato.stanford.edu/entries/seneca/
Paradoxes and Contemporary Logic https://plato.stanford.edu/entries/paradoxes-contemporary-logic/
Dynamic Choice https://plato.stanford.edu/entries/dynamic-choice/
Facts https://plato.stanford.edu/entries/facts/
The Logic of Conditionals https://plato.stanford.edu/entries/logic-conditionals/
Combining Logics https://plato.stanford.edu/entries/logic-combining/
Convention https://plato.stanford.edu/entries/convention/
Contractualism https://plato.stanford.edu/entries/contractualism/
The Value of Knowledge https://plato.stanford.edu/entries/knowledge-value/
Loyalty https://plato.stanford.edu/entries/loyalty/
The Unity of Science https://plato.stanford.edu/entries/scientific-unity/
Moral Anti-Realism https://plato.stanford.edu/entries/moral-anti-realism/
Incommensurable Values https://plato.stanford.edu/entries/value-incommensurable/
Speech Acts https://plato.stanford.edu/entries/speech-acts/
Discourse Representation Theory https://plato.stanford.edu/entries/discourse-representation-theory/
The Meaning of Life https://plato.stanford.edu/entries/life-meaning/
Fictionalism https://plato.stanford.edu/entries/fictionalism/
Psychologism https://plato.stanford.edu/entries/psychologism/
Monism https://plato.stanford.edu/entries/monism/
Presocratic Philosophy https://plato.stanford.edu/entries/presocratics/
Naturalism https://plato.stanford.edu/entries/naturalism/
Situations in Natural Language Semantics https://plato.stanford.edu/entries/situations-semantics/

Metaethics https://plato.stanford.edu/entries/metaethics/
Assertion https://plato.stanford.edu/entries/assertion/
Wisdom https://plato.stanford.edu/entries/wisdom/
Social Institutions https://plato.stanford.edu/entries/social-institutions/
Civil Disobedience https://plato.stanford.edu/entries/civil-disobedience/
Concepts of God https://plato.stanford.edu/entries/concepts-god/
Pragmatics https://plato.stanford.edu/entries/pragmatics/
Jacques Derrida https://plato.stanford.edu/entries/derrida/
The Problem of Induction https://plato.stanford.edu/entries/induction-problem/
Self-Deception https://plato.stanford.edu/entries/self-deception/
Citizenship https://plato.stanford.edu/entries/citizenship/
Population Genetics https://plato.stanford.edu/entries/population-genetics/
Linear Logic https://plato.stanford.edu/entries/logic-linear/
Nonexistent Objects https://plato.stanford.edu/entries/nonexistent-objects/
Belief https://plato.stanford.edu/entries/belief/
Evidence https://plato.stanford.edu/entries/evidence/
Democracy https://plato.stanford.edu/entries/democracy/
Intensional Logic https://plato.stanford.edu/entries/logic-intensional/
Pacifism https://plato.stanford.edu/entries/pacifism/
Japanese Zen Buddhist Philosophy https://plato.stanford.edu/entries/japanese-zen/
Contradiction https://plato.stanford.edu/entries/contradiction/
Hybrid Logic https://plato.stanford.edu/entries/logic-hybrid/
Truth https://plato.stanford.edu/entries/truth/
Moral Naturalism https://plato.stanford.edu/entries/naturalism-moral/
Logical Truth https://plato.stanford.edu/entries/logical-truth/
Colonialism https://plato.stanford.edu/entries/colonialism/
Types and Tokens https://plato.stanford.edu/entries/types-tokens/
Logic of Belief Revision https://plato.stanford.edu/entries/logic-belief-revision/
Pythagoreanism https://plato.stanford.edu/entries/pythagoreanism/
The Limits of Law https://plato.stanford.edu/entries/law-limits/
Models in Science https://plato.stanford.edu/entries/models-science/
Trust https://plato.stanford.edu/entries/trust/
The Repugnant Conclusion https://plato.stanford.edu/entries/repugnant-conclusion/
Aristotle&rsquo;s Biology https://plato.stanford.edu/entries/aristotle-biology/
African Sage Philosophy https://plato.stanford.edu/entries/african-sage/
Coercion https://plato.stanford.edu/entries/coercion/
Sortals https://plato.stanford.edu/entries/sortals/
Type Theory https://plato.stanford.edu/entries/type-theory/
Deontic Logic https://plato.stanford.edu/entries/logic-deontic/
Torture https://plato.stanford.edu/entries/torture/
Samuel Ibn Tibbon https://plato.stanford.edu/entries/tibbon/
Bernard Williams https://plato.stanford.edu/entries/williams-bernard/
Emotions in the Christian Tradition https://plato.stanford.edu/entries/emotion-Christian-tradition/
Maimonides https://plato.stanford.edu/entries/maimonides/
Eternity in Christian Thought https://plato.stanford.edu/entries/eternity/
Robin George Collingwood https://plato.stanford.edu/entries/collingwood/
Aristotle on Causality https://plato.stanford.edu/entries/aristotle-causality/
Political Representation https://plato.stanford.edu/entries/political-representation/
Axiomatic Theories of Truth https://plato.stanford.edu/entries/truth-axiomatic/
Personal Identity and Ethics https://plato.stanford.edu/entries/identity-ethics/
Rights https://plato.stanford.edu/entries/rights/
Propositions https://plato.stanford.edu/entries/propositions/
Pleasure https://plato.stanford.edu/entries/pleasure/
Locke's Political Philosophy https://plato.stanford.edu/entries/locke-political/
Hermeneutics https://plato.stanford.edu/entries/hermeneutics/
Concepts https://plato.stanford.edu/entries/concepts/
Monotheism https://plato.stanford.edu/entries/monotheism/
Other Minds https://plato.stanford.edu/entries/other-minds/
Moral Realism https://plato.stanford.edu/entries/moral-realism/
Postmodernism https://plato.stanford.edu/entries/postmodernism/
Pain https://plato.stanford.edu/entries/pain/
Socrates https://plato.stanford.edu/entries/socrates/
Ancient Atomism https://plato.stanford.edu/entries/atomism-ancient/
Units and Levels of Selection https://plato.stanford.edu/entries/selection-units/
Collective Responsibility https://plato.stanford.edu/entries/collective-responsibility/
Continuity and Infinitesimals https://plato.stanford.edu/entries/continuity/
Supervenience https://plato.stanford.edu/entries/supervenience/
Omnipresence https://plato.stanford.edu/entries/omnipresence/
Justice and Bad Luck https://plato.stanford.edu/entries/justice-bad-luck/
Logical Constants https://plato.stanford.edu/entries/logical-constants/
Possible Objects https://plato.stanford.edu/entries/possible-objects/
Identity Over Time https://plato.stanford.edu/entries/identity-time/
The Contents of Perception https://plato.stanford.edu/entries/perception-contents/
Critical Theory https://plato.stanford.edu/entries/critical-theory/
The Problem of Perception https://plato.stanford.edu/entries/perception-problem/
Phenomenological Approaches to Self-Consciousness https://plato.stanford.edu/entries/self-consciousness-phenomenological/
Neutral Monism https://plato.stanford.edu/entries/neutral-monism/
Defeasible Reasoning https://plato.stanford.edu/entries/reasoning-defeasible/
Epicurus https://plato.stanford.edu/entries/epicurus/
Logical Consequence https://plato.stanford.edu/entries/logical-consequence/
Identity https://plato.stanford.edu/entries/identity/
Inverted Qualia https://plato.stanford.edu/entries/qualia-inverted/
Skepticism and Content Externalism https://plato.stanford.edu/entries/skepticism-content-externalism/
Simplicity https://plato.stanford.edu/entries/simplicity/
Game Theory and Ethics https://plato.stanford.edu/entries/game-ethics/
Substance https://plato.stanford.edu/entries/substance/
Inductive Logic https://plato.stanford.edu/entries/logic-inductive/
Property and Ownership https://plato.stanford.edu/entries/property/
Dialectical School https://plato.stanford.edu/entries/dialectical-school/
Functionalism https://plato.stanford.edu/entries/functionalism/
Existentialism https://plato.stanford.edu/entries/existentialism/
Rationalism vs. Empiricism https://plato.stanford.edu/entries/rationalism-empiricism/
Reism https://plato.stanford.edu/entries/reism/
Bell's Theorem https://plato.stanford.edu/entries/bell-theorem/
Cosmological Argument https://plato.stanford.edu/entries/cosmological-argument/
Foreknowledge and Free Will https://plato.stanford.edu/entries/free-will-foreknowledge/
Authority https://plato.stanford.edu/entries/authority/
Computability and Complexity https://plato.stanford.edu/entries/computability/
Consciousness https://plato.stanford.edu/entries/consciousness/
Categories https://plato.stanford.edu/entries/categories/
Schema https://plato.stanford.edu/entries/schema/
Sense-Data https://plato.stanford.edu/entries/sense-data/
Suicide https://plato.stanford.edu/entries/suicide/
Pornography and Censorship https://plato.stanford.edu/entries/pornography-censorship/
Compatibilism https://plato.stanford.edu/entries/compatibilism/
Hedonism https://plato.stanford.edu/entries/hedonism/
Plato https://plato.stanford.edu/entries/plato/
The Chinese Room Argument https://plato.stanford.edu/entries/chinese-room/
Atheism and Agnosticism https://plato.stanford.edu/entries/atheism-agnosticism/
Descriptions https://plato.stanford.edu/entries/descriptions/
Anaphora https://plato.stanford.edu/entries/anaphora/
The Frame Problem https://plato.stanford.edu/entries/frame-problem/
Moral Relativism https://plato.stanford.edu/entries/moral-relativism/
Boundary https://plato.stanford.edu/entries/boundary/
Temporal Parts https://plato.stanford.edu/entries/temporal-parts/
Knowledge by Acquaintance vs. Description https://plato.stanford.edu/entries/knowledge-acquaindescrip/
Rule Consequentialism https://plato.stanford.edu/entries/consequentialism-rule/
Francis Bacon https://plato.stanford.edu/entries/francis-bacon/
Legal Obligation and Authority https://plato.stanford.edu/entries/legal-obligation/
Plato on Rhetoric and Poetry https://plato.stanford.edu/entries/plato-rhetoric/
Mental Causation https://plato.stanford.edu/entries/mental-causation/
Phenomenology https://plato.stanford.edu/entries/phenomenology/
Arguments for Incompatibilism https://plato.stanford.edu/entries/incompatibilism-arguments/
Practical Reason https://plato.stanford.edu/entries/practical-reason/
Moral Reasoning https://plato.stanford.edu/entries/reasoning-moral/
Zombies https://plato.stanford.edu/entries/zombies/
Nothingness https://plato.stanford.edu/entries/nothingness/
Karl Marx https://plato.stanford.edu/entries/marx/
Dualism https://plato.stanford.edu/entries/dualism/
Life https://plato.stanford.edu/entries/life/
Necessary and Sufficient Conditions https://plato.stanford.edu/entries/necessary-sufficient/
The Analytic/Synthetic Distinction https://plato.stanford.edu/entries/analytic-synthetic/
Intentionality https://plato.stanford.edu/entries/intentionality/
Virtue Ethics https://plato.stanford.edu/entries/ethics-virtue/
States of Affairs https://plato.stanford.edu/entries/states-of-affairs/
The Moral Status of Animals https://plato.stanford.edu/entries/moral-animal/
The Computational Theory of Mind https://plato.stanford.edu/entries/computational-mind/
Bayes' Theorem https://plato.stanford.edu/entries/bayes-theorem/
Punishment https://plato.stanford.edu/entries/punishment/
Sovereignty https://plato.stanford.edu/entries/sovereignty/
The Free Rider Problem https://plato.stanford.edu/entries/free-rider/
Consequentialism https://plato.stanford.edu/entries/consequentialism/
Mereology https://plato.stanford.edu/entries/mereology/
Eliminative Materialism https://plato.stanford.edu/entries/materialism-eliminative/
Laws of Nature https://plato.stanford.edu/entries/laws-of-nature/
The Turing Test https://plato.stanford.edu/entries/turing-test/
Analysis https://plato.stanford.edu/entries/analysis/
Memory https://plato.stanford.edu/entries/memory/
Aesthetic Judgment https://plato.stanford.edu/entries/aesthetic-judgment/
Positive and Negative Liberty https://plato.stanford.edu/entries/liberty-positive-negative/
Human Rights https://plato.stanford.edu/entries/rights-human/
Self-Knowledge https://plato.stanford.edu/entries/self-knowledge/
Transcendentalism https://plato.stanford.edu/entries/transcendentalism/
Civil Rights https://plato.stanford.edu/entries/civil-rights/
Emotion https://plato.stanford.edu/entries/emotion/
Relativism https://plato.stanford.edu/entries/relativism/
Causal Determinism https://plato.stanford.edu/entries/determinism-causal/
Nonconceptual Mental Content https://plato.stanford.edu/entries/content-nonconceptual/
Reference https://plato.stanford.edu/entries/reference/
Moral Character https://plato.stanford.edu/entries/moral-character/
Federalism https://plato.stanford.edu/entries/federalism/
Legal Positivism https://plato.stanford.edu/entries/legal-positivism/
Change and Inconsistency https://plato.stanford.edu/entries/change/
Fatalism https://plato.stanford.edu/entries/fatalism/
Law and Language https://plato.stanford.edu/entries/law-language/
Freedom of Speech https://plato.stanford.edu/entries/freedom-speech/
Time https://plato.stanford.edu/entries/time/
Structuralism in Physics https://plato.stanford.edu/entries/physics-structuralism/
Narrow Mental Content https://plato.stanford.edu/entries/content-narrow/
The Pure Theory of Law https://plato.stanford.edu/entries/lawphil-theory/
Paternalism https://plato.stanford.edu/entries/paternalism/
Egoism https://plato.stanford.edu/entries/egoism/
Intrinsic vs. Extrinsic Value https://plato.stanford.edu/entries/value-intrinsic-extrinsic/
Externalism About Mental Content https://plato.stanford.edu/entries/content-externalism/
Children&rsquo;s Rights https://plato.stanford.edu/entries/rights-children/
Equality of Opportunity https://plato.stanford.edu/entries/equal-opportunity/
Parenthood and Procreation https://plato.stanford.edu/entries/parenthood/
Civic Humanism https://plato.stanford.edu/entries/humanism-civic/
Object https://plato.stanford.edu/entries/object/
Emergent Properties https://plato.stanford.edu/entries/properties-emergent/
The Natural Law Tradition in Ethics https://plato.stanford.edu/entries/natural-law-ethics/
Libertarianism https://plato.stanford.edu/entries/libertarianism/
Qualia: The Knowledge Argument https://plato.stanford.edu/entries/qualia-knowledge/
Personal Identity https://plato.stanford.edu/entries/identity-personal/
Egalitarianism https://plato.stanford.edu/entries/egalitarianism/
Pyrrho https://plato.stanford.edu/entries/pyrrho/
Identity Politics https://plato.stanford.edu/entries/identity-politics/
Realism https://plato.stanford.edu/entries/realism/
Consciousness and Intentionality https://plato.stanford.edu/entries/consciousness-intentionality/
Moral Skepticism https://plato.stanford.edu/entries/skepticism-moral/
Scientific Realism https://plato.stanford.edu/entries/scientific-realism/
Personal Autonomy https://plato.stanford.edu/entries/personal-autonomy/
The Biological Notion of Self and Non-self https://plato.stanford.edu/entries/biology-self/
Omnipotence https://plato.stanford.edu/entries/omnipotence/
Doing vs. Allowing Harm https://plato.stanford.edu/entries/doing-allowing/
Privacy https://plato.stanford.edu/entries/privacy/
The Correspondence Theory of Truth https://plato.stanford.edu/entries/truth-correspondence/
Determinables and Determinates https://plato.stanford.edu/entries/determinate-determinables/
Events https://plato.stanford.edu/entries/events/
Relative Identity https://plato.stanford.edu/entries/identity-relative/
The Definition of Morality https://plato.stanford.edu/entries/morality-definition/
Moral Dilemmas https://plato.stanford.edu/entries/moral-dilemmas/
Finitism in Geometry https://plato.stanford.edu/entries/geometry-finitism/
Process Philosophy https://plato.stanford.edu/entries/process-philosophy/
Justice as a Virtue https://plato.stanford.edu/entries/justice-virtue/
Free Will https://plato.stanford.edu/entries/freewill/
Intrinsic vs. Extrinsic Properties https://plato.stanford.edu/entries/intrinsic-extrinsic/
Affirmative Action https://plato.stanford.edu/entries/affirmative-action/
Legal Rights https://plato.stanford.edu/entries/legal-rights/
Skepticism https://plato.stanford.edu/entries/skepticism/
Nationalism https://plato.stanford.edu/entries/nationalism/
Model Theory https://plato.stanford.edu/entries/model-theory/
First-order Model Theory https://plato.stanford.edu/entries/modeltheory-fo/
Tarski's Truth Definitions https://plato.stanford.edu/entries/tarski-truth/
Causation in the Law https://plato.stanford.edu/entries/causation-law/
Well-Being https://plato.stanford.edu/entries/well-being/
Communitarianism https://plato.stanford.edu/entries/communitarianism/
John Locke https://plato.stanford.edu/entries/locke/
Common Knowledge https://plato.stanford.edu/entries/common-knowledge/
Comparative Philosophy: Chinese and Western https://plato.stanford.edu/entries/comparphil-chiwes/
Abstract Objects https://plato.stanford.edu/entries/abstract-objects/
Automated Reasoning https://plato.stanford.edu/entries/reasoning-automated/
Panpsychism https://plato.stanford.edu/entries/panpsychism/
Higher-Order Theories of Consciousness https://plato.stanford.edu/entries/consciousness-higher/
The Unity of Consciousness https://plato.stanford.edu/entries/consciousness-unity/
Equality https://plato.stanford.edu/entries/equality/
Physicalism https://plato.stanford.edu/entries/physicalism/
The Analysis of Knowledge https://plato.stanford.edu/entries/knowledge-analysis/
Challenges to Metaphysical Realism https://plato.stanford.edu/entries/realism-sem-challenge/
Constitutionalism https://plato.stanford.edu/entries/constitutionalism/
Counterfactual Theories of Causation https://plato.stanford.edu/entries/causation-counterfactual/
Disjunction https://plato.stanford.edu/entries/disjunction/
Incompatibilist (Nondeterministic) Theories of Free Will https://plato.stanford.edu/entries/incompatibilism-theories/
Contractarianism https://plato.stanford.edu/entries/contractarianism/
Actualism https://plato.stanford.edu/entries/actualism/
Representational Theories of Consciousness https://plato.stanford.edu/entries/consciousness-representational/
Mental Representation https://plato.stanford.edu/entries/mental-representation/
War https://plato.stanford.edu/entries/war/
The Mind/Brain Identity Theory https://plato.stanford.edu/entries/mind-identity/
Logical Form https://plato.stanford.edu/entries/logical-form/
Properties https://plato.stanford.edu/entries/properties/
Intuitionistic Logic https://plato.stanford.edu/entries/logic-intuitionistic/
Epiphenomenalism https://plato.stanford.edu/entries/epiphenomenalism/
The Language of Thought Hypothesis https://plato.stanford.edu/entries/language-thought/
Pascal's Wager https://plato.stanford.edu/entries/pascal-wager/
Color https://plato.stanford.edu/entries/color/
Mental Imagery https://plato.stanford.edu/entries/mental-imagery/
Structured Propositions https://plato.stanford.edu/entries/propositions-structured/
Qualia https://plato.stanford.edu/entries/qualia/
Singular Propositions https://plato.stanford.edu/entries/propositions-singular/
Probabilistic Causation https://plato.stanford.edu/entries/causation-probabilistic/
Vagueness https://plato.stanford.edu/entries/vagueness/
Thought Experiments https://plato.stanford.edu/entries/thought-experiment/
Causal Processes https://plato.stanford.edu/entries/causation-process/
Liberalism https://plato.stanford.edu/entries/liberalism/
Informal Logic https://plato.stanford.edu/entries/logic-informal/
Logical Constructions https://plato.stanford.edu/entries/logical-construction/
The Coherence Theory of Truth https://plato.stanford.edu/entries/truth-coherence/
Existence https://plato.stanford.edu/entries/existence/
The Identity of Indiscernibles https://plato.stanford.edu/entries/identity-indiscernible/
Stoicism https://plato.stanford.edu/entries/stoicism/
The Identity Theory of Truth https://plato.stanford.edu/entries/truth-identity/
Contemporary Approaches to the Social Contract https://plato.stanford.edu/entries/contractarianism-contemporary/
Original Position https://plato.stanford.edu/entries/original-position/
Animal Consciousness https://plato.stanford.edu/entries/consciousness-animal/

* Pre-Socratic
** Four elements: Earth, Water, Air and Fire
** Sophists ~ 450BC
[[http://en.wikipedia.org/wiki/Sophism]]
- First attempt at a full-fledged philosophical doctrine
*** Protagoras
- Considered the first sophist
*** Professional teachers
- Despised by Plato
  - Because they charged fees
  - Because they used rhetorical sleight-of-hand
** Pythagoreans ~ 500BC
[[http://en.wikipedia.org/wiki/Pythagoreans]]
- Believed in reincarnation
- Heavily influenced by mathematics and mysticism
- Transmigration of the Soul was a core belief
- Were vegetarians
** Heraclitus - 535-475BC
[[http://en.wikipedia.org/wiki/Heraclitus]]
- "No man steps in the same river twice."
- Diogenes primary biographer
** Parmenides ~ 450BC
[[http://en.wikipedia.org/wiki/Parmenides]]
- Only known work was "On Nature" - a poem
- Claimed that truth cannot be know through sensory perception, only through logos.
** Zeno of Elea - 490-430BC
[[http://en.wikipedia.org/wiki/Zeno]]
*** Reducto ad Absurdum
*** Zeno's Paradox
- Arhilles and the Tortoise
[[http://en.wikipedia.org/wiki/Zeno%27s_paradoxes#Achilles_and_the_tortoise]]
** Herodotus - 484-425BC
[[http://en.wikipedia.org/wiki/Herodotus]]
- Greek Historian
- First known writer to collect and document his ideas systematically.
** Thucydides - 460-395BC
[[http://en.wikipedia.org/wiki/Thucydides]]
- The Pelopomnesian War - his greatest contribution to history.
- "The Father of Scientific History"
- "The Father of the school of political realism"
* Classical Greek
** Socrates - 469-399BC
[[http://en.wikipedia.org/wiki/Socrates]]
- Ethical truth was absolute
- "To Know the Good is to Do the Good"
** Plato
[[http://en.wikipedia.org/wiki/Plato]]
- Invented Metaphysics
- The Socratic Method
- Forms
- Asked the question "What is virtue?"
- Invented Dualism of Mind and Body
*** Republic
- Shadows on the Cave Wall
- Women should hold political power
- Political leaders chosen from among best & brightest
- Anti-democratic
- What is Justice?
  - Give each man his due
  - Might makes right
  - Reason
- No nuclear family
- No private property
- Philosopher "guardians" of Reason will rule
** Aristotle
[[http://en.wikipedia.org/wiki/Aristotle]]
- Democratic principles
- Invented term "physics"
  - Greek for "Nature"
*** Criticism of The Republic/Plato
- Family is rooted in human nature
- Idea of private property is 'natural'
- Rejected concentration of power
- Supported rule by middle class
*** Ethics
- Defined ethics as "What is the good goal of human life?"
- Happiness is the life lived by the virtuous person
- Happiness is the goal of human life
  - Happiness originally meant "success"
- Happiness means good at being human
**** Four Primary Virtues
  - Courage
  - Temperance
  - Justice
  - Wisdom
*** Epistomology
- We acquire our knowledge of the world via our senses
** Epicureanism
[[http://en.wikipedia.org/wiki/Epicureanism]]
- We are made of atoms
- No afterlife
- Abstain from Political Life
- Abstain from sexual involvement
- Take nothing to excess
** Stoicism
[[http://en.wikipedia.org/wiki/Stoicism]]
- Critical response to epicureanism
- Freedom from suffering through discipline
- Duty to community
- Considered philosophy a way of life
- Actions more important than beliefs
*** Zeno of Citium - 334-262BC
[[http://en.wikipedia.org/wiki/Zeno_of_Citium]]
- Considered founder of Stoicism
- "Happiness is a good flow of life"
- Pathos is a disturbance of the mind repugnant to Reason and against Nature.
- Virtua is the consistency of the soul with Right Reason and Universal Reason
  (logic)
*** Zeno of Elea - 490-430BC
[[http://en.wikipedia.org/wiki/Zeno_of_Elea]]
- Realist/Materialist
- Best known for his Paradoxes
[[http://en.wikipedia.org/wiki/Zeno%27s_paradoxes]]
* Romans
** Cicero - 106-43BC
[[http://en.wikipedia.org/wiki/Cicero]]
- Brought Greek philosophy to the Romans
- Combined Skeptics, Epicureanism
- Virtue is happiness from Aristotle
- Epicurean principle of refined and disciplined pleasure
** Skeptics
[[http://en.wikipedia.org/wiki/Skeptics]]
- Sextus Empiricus
- Raised the question "How do we know what we know?"
- Can we trust any of our own knowledge?
* Christians
** Hebrew Bible
[[http://en.wikipedia.org/wiki/Hebrew_Bible]]
- Explores the relationship between God and the people of Jerusalem
- Central theme is the Covenant
*** Abraham
- Isaac
  - Jacob (Israel)
** Old Testament
[[http://en.wikipedia.org/wiki/Old_Testament]]
*** Book of Job
[[http://en.wikipedia.org/wiki/Book_of_Job]]
- Asks the question "Why do the righteous suffer?"
- Satan challenges Lord
- Lord inflicts cruelty on Job
- Job does not forsake his Lord
** New Testament
[[http://en.wikipedia.org/wiki/New_Testament]]
*** Paul
- Early author
- The Gospels
- Baptism as the means by which Jews become Christians
- Rejects circumcision as a necessary rite to become Christian
** Augistine - 354 - 430
[[http://en.wikipedia.org/wiki/Augustine]]
- Combined christian with platonic
- Wrote "Confessions" [[http://en.wikipedia.org/wiki/Confessions_of_St._Augustine]]
- The Grace of God
- Is grace a gift of god, or must it be earned?
- Predestination - God knows from the start who will receive The Grace
** Aquinus - 1225-1274
[[http://en.wikipedia.org/wiki/Aquinas]]
- Argues that the eternity of the world cannot be demonstrated by pure logic.
- Wrote the "Summa Theologica"
- Aristotelian
- Truth could be achieved through natural or divine reason
*** Four Cardinal Virtues
- Prudence
- Temperance
- Justice
- Fortitude
*** Five Ways on the Nature of God
- God is simple, without composition of parts
- God is perfect, lacking nothing
- God is infinite
- God is immutable
- God is one
** Medieval Thought
*** Realism
- Words have meaning in and of themselves
*** Nominalism
- Words have no inherit meaning
** Luther - 1483-1546
[[http://en.wikipedia.org/wiki/Luther]]
- Disagreed with Augustine's automatic granting of grace by god
*** Wrote the 95 Theses
- In response to Indulgences sold by the Pope
- Strongly believed that freedom from God's punishment could not be purchased with
  money.
*** Earned grace through belief in Jesus
- Salvation is not earned by good deeds
- Faith in Jesus brings salvation
*** Once justified, you can be condemned  through the commission of sin.
** Calvin - 1509-1564
[[http://en.wikipedia.org/wiki/Calvin]]
- Grace was given by god
- Knowledge of God not attainable through experience, only through studying of
  scripture
- Rejected catholic doctrine of merit
- Supported the notion of predestination
- Once justified, always justified
- Justification comes through having a conversion experience
- Proponent of the concept of the original sin
* The Renaissance
** Machiavelli
[[http://en.wikipedia.org/wiki/Machiavelli]]
- Inventor of Political Science
*** The Prince
- "It is better to be feared than to be loved, because love is fickle but fear is
  constant.
- Reputation for honesty, integrity is important
- But not the practice of it.
** Thomas Moore
[[http://en.wikipedia.org/wiki/Thomas_Moore]]
*** Wrote "Utopia"
- Mocked modern English society
- All property is communal
- Marriage is by love, not arranged
- Elected parliament
- Price elected for life
- Moral Theory focused on happiness
**** War for 3 Reasons
  - Defend Territory
  - Defend Ally Territory
  - Liberate oppressed people
** Erasumus
[[http://en.wikipedia.org/wiki/Erasmus]]
- Opposed strong enthusiasms
** Galileo
[[http://en.wikipedia.org/wiki/Galileo]]
** Francis Bacon
[[http://en.wikipedia.org/wiki/Francis_Bacon]]
- Sought to separate religion from natural philosophy
- Stressed Induction and Experimetnal Methods
- Father of Emperecism
- Strong advocate of inductive reasoning
- The father of emperecism
** Descartes
[[http://en.wikipedia.org/wiki/Descartes]]
- "Cogito ergo sum"
  - The most basic of all ideas, the existence of which cannot be disputed
- Two Proofs of God
  - A perfect being could only come from a perfect being.
  - From necessity: a perfect being must have existence to be perfect.
- Dualist (Mind/Body Dualism)
** Hobbes
[[http://en.wikipedia.org/wiki/Hobbes]]
- Leviathan
- We are guided by passions, not reason
- Passions
  - Desire for Power
  - Fear of Death
- Government is a means of escaping struggle between power and fear
- Governments derive their power from the subjects in exchange for peace and security
- The Social Contract
- Brutish, solitary and short.
** Spinoza
[[http://en.wikipedia.org/wiki/Spinoza]]
- Condemned by the Sephardic Jews of Amsterdam as a heretic.
- Freewill is a logical impossibility because all causes have precedents
- Rejected dualism of Descartes
*** God vs Nature
- God is nature
- All there is, is nature
- Nature has no values - good or bad
  - Nature simply is
- "The wise man seeks to understand nature, not gape at it like a fool."
*** Hell and damnation
- A life dominated by the original sin is a life of bondage, not rational freedom.
- There is no afterlife or an immortal soul.
*** Passion vs Reason
- A people lead by passion are more easily manipulated.
- Denied that the bible was the literal word of god.
*** Religion and virtue
- What you believe is not important
- Only what you believe matters.
*** Freedom
- Freedom to philosophise was the mark of a free society.
- Freedom of expression should be granted to all. Including religious freedom.
- Any government that attempts to manipulate the minds of men is a tyranny.
- All that matters is the right of the individual.
- Attempts to control either speech or thought will end in failure.
- Governments should only be able to interfere with men's actions, not their thoughts
  or words.
** Bayle
[[http://en.wikipedia.org/wiki/Pierre_Bayle]]
- Skepticism
- What do we know with any certainty?
- God cannot be known via reason, only faith
** Newton
[[http://en.wikipedia.org/wiki/Isaac_Newton]]
- Principia
- Law of Gravity
- Laws of Motion
- Discovered calculus
- Modern optics
* The Enlightenment
** Adam Smith - 1723-1790
[[http://en.wikipedia.org/wiki/Adam_smith]]
- He was aware of the dangers and problems that could arise from too much
  specialization of labor and the social isolation that could result.
- He worried about the moral impact on someone who shifted from a village-centric
  social context to that of a large city and the anonymity that could result.
- Smith is also concerned about class and wealth disparity and that impacts that
  would have on society.
*** The Theory of Moral Sentiment
- Offers an explanation and basis for the cooperation and coordination that are
  required for the division of labor described in Wealth of Nations.
- Why?
  - We want the approval of others
  - The reactions of others to us and our behaviors is important to us.
  - We generally seek to behave as if there were an impartial spectator observing our behaviors. Would they approve of them?
  - Our conscience is a product of these factors.
- Obeying the law
  - We do so because of the utility of doing so. In general, we derive benefit when we do so.
*** The Wealth of Nations: The Division of Labor
- Specialization of job function leads to massive gains in efficiency.
- Coordination and cooperation between specialists is done out of self-interest.
- We get what we need from others out of their self-interest, not their charity.
** Rousseau - 1712-1778
[[http://en.wikipedia.org/wiki/Rousseau]]
- Claimed that enlightenment beliefs led to eventual collapse of civilizations
- Called for a return to nature
*** Critiqued the progress of modern society
- Moral decadence always accompanies cultural progress
- American Indians in their simplistic life compare favorably to Europeans in their
  levels of happiness and virtue.
*** Social Contract
- All power is given to the state
- Your happiness is calculated as your share of the overall societal happiness
** David Hume - 1711-1766
[[http://en.wikipedia.org/wiki/David_Hume]]
*** Epistemology
- Ideas are copies of our sense impressions
- Three relations among ideas
  - Resemblance
  - Spatio-temporal
  - Cause-effect
- Reason alone cannot justify our belief in experience
- Belief in our experiences as representing the external world accurately is based on
  our instinct or custom, and cannot be proven with reason.
*** Morality
- Scientific theory of morality
- Moral judgment cannot be based on rational deliberation, because simpletons and
  infants are also capable of making more judgments.
- There is no evidence that indicates that the most intellectually capable members of
  our species are the most moral.
- Therefore, our sense of morality is based in part on our biology and in part by our
  social context.
- What makes a moral rule a universal more rule?
  - Primarily, its utility
  - All government and political institutions have their basis in utility to society.
- We have a natural appreciation for virtuous behavior, and are thus naturally moral
  at least in part.
- You cannot deterministically go from an "is" to an "ought"
*** Religion
- Basing religious belief on inference from experience has four flaws
  - It means that religion is probable at best, because all ideas are derived from experience, not reason.
  - In all scientific inquiries, negative evidence counts more than positive evidence. So we would require positive evidence with zero negative evidence in order to justify our belief in god through experience.
- Effects do not prove a cause.
- In the end, Hume is dismissive of both religion in general and in the ability to
  base religious belief on experience.
** Montesquieu - 1689-1755
[[http://en.wikipedia.org/wiki/Montesquieu]]
- Objected to Locke's Epistemological Relativism
- The laws of nature are demonstrable across cultures, therefore not all knowledge is
  relative
- Believed that democratic republics are the most morally desirable but least stable
  forms of association
- Greatly influenced American Revolution
  - Must limit the ability of government to grow in power
- Affluence eventually leads to despotism
** Bishop Berkeley - 1685-1733
[[http://en.wikipedia.org/wiki/Bishop_Berkeley]]
- There is no existence independent of perception
- To exist is to be perceived
- Disagreed with Locke's argument that human knowledge depends on the existence of
  material objects independent of minds.
- Claimed that materialism was dogmatic superstition.
- All of our ideas are derived from our experiences
** Mandeville - 1670-1733
[[http://en.wikipedia.org/wiki/Bernard_Mandeville]]
- The Fable of the Bees
- Central Human Traits
  - Selfishness
  - Egocentrism
** Vico - 1678-1744
[[http://en.wikipedia.org/wiki/Giambattista_Vico]]
- Philosophy of history
*** Human societies are cyclical
- Worship of gods
- Emergence of Heroes and kings
- Age of man
  - Inherently unstable
  - Leads to collapse
*** Disagreed with social contract theory
- Society is not a contract but the natural progression from customs and mores
** Leibniz - 1646-1716
[[http://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz]]
*** Co-inventory of Infinitesimal Calculus
[[http://en.wikipedia.org/wiki/Infinitesimal_calculus]]
*** Asserted "The best of all possible worlds"
[[http://en.wikipedia.org/wiki/Best_of_all_possible_worlds]]
*** Metaphyics - La Monadologie
[[http://en.wikipedia.org/wiki/Monadology]]
- An attempt to resolve the problem of mind/body dualism
- Nothing arises from nothing
- Everything that exists has a reason to exist
- Everything which exists is better than anything non-existent
*** Théodicée
[[http://en.wikipedia.org/wiki/Th%C3%A9odic%C3%A9e]]
- Reason and faith are gifts from God
- Sin and Suffering are the result of metaphysical imperfections
- Although God has unlimited reason and willpower, humans do not which makes sin and
  suffering possible.
*** Early developer of formal/algebraic logic
[[http://en.wikipedia.org/wiki/Algebraic_logic]]
** John Locke - 1632-1704
[[http://en.wikipedia.org/wiki/John_locke]]
*** Politics
- A man is free when he is subject only to political authority to which he has
  consented.
- Natural liberty is freedom from the arbitrary power of others
- Beginning of modern democratic political theory.
- Denies need for authoritarian power, which leads to despotism and tyranny
- Denies that fear is the primary motivator of men
- Natural Rights
  - Life
  - Liberty
  - Property
- Men are governed by laws from a legislature
- Opposed monarchies
- Modern social contract theory
  - An agreement among free and equal men to exit the state of nature and by forming a limited polity.
- Stressed that equality was legal equality, not equality of material possessions.
*** Knowledge/Epistomology
- Empericist
- Ideas are acquired via experience
- Two forms of experience
  - The external world
  - Reflection on the mind's own operations
- There are no innate ideas
- The mind is a Tabula Rasa
*** Ethics
- Ethics are learned, not innate
- Ethics are derived from experience, and thus relative to our experience of the
  world
* Age of Ideology
** Kant
[[http://en.wikipedia.org/wiki/Emmanuel_Kant]]
*** The Critique of Pure Reason
- Science is the study of the world as perceived by our senses
- To experience that world, we impose upon it forms and categories that make our
  experience of the world possible and coherent.
  - Space and Time
  - Object Persistence
  - Causality
  - Existence
  - Plurality
  - Unity
- Metaphysics goes beyond our experience, and thus outside of pure reason
- Disagreed with Locke and Hume and their empericism - the idea that all ideas and
  truths come from experience
- Without his 'categories of understanding' none of our experiences would make any
  sense.
*** The Critique of Practical Reason
- Maxim: Act only that that maxim by which you can at the same time will that it
  become a universal law.
- Practical Reason is concerned with how we ought to live.
- A moral law cannot consist primarily of hypothetical imperatives
  - Ex: If you want to stay healthy, you should eat right and exercise.
  - Ex: If you want to become a doctor, than you should study.
- Hypothetical imperatives fail because they only apply to those who want the outcome
  they describe.
- Categorical Imperatives have no qualification clause
  - Instead of saying "Do not lie if you want to be trusted" (hypothetical), instead it should be "Do not lie".
  - Categorical Imperatives must not depend on circumstance, desire or on the consequences of their actions
- The notion of Free Will is justified by our ability to self-legislate - to create
  rules that we should follow, and then to follow them.
*** Freedom, Morality
[[http://reasonandmeaning.com/2015/03/29/finally-kants-ethics-in-two-pages/]]
- Without freedom, morality is not possible
- Morality exists
- Therefore, freedom must exist
** Burke
[[http://en.wikipedia.org/wiki/Edmund_Burke]]
- Strongly condemned the French Revolution
- Strongly supported of the American Revolution
  - Because it did not propose a social upheaval or overturn, only a political one.
  - He believed that is used as its basis the notion of traditional rights - no taxation without representation - derived from English common law.
- Believed that individual rights were not derived from abstract principles but were
  instead based on traditions and conventions of the population.
- These are 'conventional' rights that could not be derived from theory.
** Hegel
[[http://en.wikipedia.org/wiki/Hegel]]
- Founder of Modern Historicism
- Opposed the Enlightenment concepts of materialism and that the unfolding of history
  was purely mechanical.
** Marx
[[http://en.wikipedia.org/wiki/Marx]]
- Historical materialism
- Division of Labor
- There will always be a scarcity of the goods needed to satisfy the cultural wants
  of all of society.
  - A consequence of this is that one part of society establishes itself as a ruling class in order to secure a dispropotionate share. This is inevitable as human nature
- Felt that the downfall of Capitalism was inevitable. And that Communism was its
  logical successor.
- Capitalism leads to exploitation and inequality, especially for women.
*** Modes of Production
- Communism is the answer to the problems inherit in the Capitalist Mode of
  Production.
- It addresses the problem of disparate incomes.
- It addresses the problem of scarcity on a global basis.
*** Felt that Capitalism would lead to alienation.
- Capitalism and Private Property would alienate man from other men and from himself.
** Mill - 1806-1873
[[http://en.wikipedia.org/wiki/John_Stuart_Mill]]
- Wrote "On Liberty" - classical defense of freedom from intrusive government AND
  from majority rule.
- Main defender of Utilitarianism
  - The idea that one ought do what brings about the most benefits and causes the least amount of harm.
  - The greatest good for the greatest number.
** Jeremey Bentham - 1748-1832
[[http://en.wikipedia.org/wiki/Jeremy_Bentham]]
- Founder of Utilitatianism
  - it is the greatest happiness of the greatest number that is the measure of right and wrong
  - Considered a hedonistic approach to utility.
- Early advocate for gender equality
- Supported the liberalization of laws against homosexuality
- Introduced the design of the Panopticon
  - [[http://en.wikipedia.org/wiki/Panopticon]]
- Coined the term "Codify"
  - proponent for condensing all British common law into a single set of cohenrent statutes.
- An early advocate of animal rights
  - A full-grown horse or dog is beyond comparison a more rational, as well as a more conversible animal, than an infant of a day, a week or even a month old. But suppose the case were otherwise, what would it avail? The question is not, Can they reason? nor, Can they talk? but, Can they suffer?
** Kierkegaard
[[http://en.wikipedia.org/wiki/Kierkegaard]]
- Founding figure of Existentialism
- Felt that true Christian faith required one to make a "Leap of Faith"
- Was concerned with Reason usurping the role and need for Faith.
- Felt that Abraham's willingness to sacrifice his only son Isaac when requested by
  God was a great "Leap of Faith"
  - Abraham's faith was justified when he raised up the knife to sacrifice his own son only to have his hand staid by God.
  - This is true belief, true faith.
- Three States to Human Life
  - Aesthetic - the pursuit of immediate pleasures.
  - Ethical - Through repentance and marriage.
  - Religious - Faith in the incarnation of God in Christ.
** Schopenhauer
[[http://en.wikipedia.org/wiki/Schopenhauer]]
- First to bring eastern Buddhist philosophy into western circles.
- Very pessimistic view of human existence.
- Believed that experiences of aesthetic beauty were as close as one could come to
  the true nature of existence.
*** Buddha's Four Noble Truths
- Life involves suffering
- Desire causes suffering
- Suffering will cease when desire ceases
- The solution to suffering is the renunciation of the will.
** Nietzsche
[[http://en.wikipedia.org/wiki/Nietzsche]]
*** Perspectivism
- Strongly rejected the Aristotelean notion of an objective real world.
- There is no true metaphysics.
- The world of appearances if the only world that we have access to.
- We have no access to knowledge about an objective world. We have only our
  perceptions, conceptions and interpretations.
- There is no 'Gods Eye View' of the real world.
  - This led to his proclomaition that 'God is Dead'
- His epistemology was practical, pragmatic.
*** The Will to Power
- Morality is an expression of The Will to Power
- Stressed master and slave morality, strength over weakness.
*** Morality is Subjective
- Values are relative to the time, place, circumstances and customs.
*** "Become who you are!"
- Ethics becomes an aesthetic pursuit of becoming a beautiful person - Give Style to
  your Character.
- We should not contradict our character, but instead cultivate our strengths and
  virtues.
- "Thus Spake Zarathustra"
- We should not follow the herd
* Modernity I
** James
[[http://en.wikipedia.org/wiki/William_James]]
- Pragmatism
- Saw his approach to philosophy as empowering the individual.
- There is no notion of absolute truth.
** Freud
[[http://en.wikipedia.org/wiki/Freud]]
- "Civilization and Its Discontents"
- Conflict among these three factions leads to unhappiness.
*** Id
- Represents the Self
- More powerful than ego, superego
- Seeks to gain pleasure, avoid pain
- Knows no moral judgements
- Produces frustration by making demands that cannot be fulfilled.
*** Ego
- Represents Reality
- Rational, cautious
- Weakest element of our personality
- Attempts to negotiate between Id and Superego
- Source of anxiety
*** Superego
- Represents Morality
- Imposes standards of moral perfection that cannot be sustained.
- It produces guilt.
** AJ Ayer
[[http://en.wikipedia.org/wiki/Alfred_Jules_Ayer]]
- Philosophy should abandon the pursuit of an absolute metaphysics.
- All talk about the world was a "logical construct" of our phenomenal and sensual
  experience.
- Considered philosophy the handmaiden of science - to help explain scientific
  meaning.
- Positivism was partly a response against the complete relativism of Kant. Positive
  = Pro-science
- Positivism was also built on the progress in symbolic logic and related
  mathematics.
- Language does not have a deterministic meaning or external provable correspondence.
- Believed that statements of ethical judgements were meaningless.
** Max Weber
[[http://en.wikipedia.org/wiki/Max_weber]]
- Founder of modern sociology
- Focused on how authority is legitimated in societies.
- Legitimacy has three forms
  - Legal
  - Traditional
  - Charismatic
** Dewey
[[http://en.wikipedia.org/wiki/John_Dewey]]
- Pragmatist
- Gave pragmatism a historical context -
- Pragmatism stats that the meaning of a statement was the practical results in
  experience that we would expect if that statement were true.
- Rejects the notion of truth and replaces it with "warranted assertability"
** Heidegger
[[http://en.wikipedia.org/wiki/Heidigger]]
** Wittgenstein
[[http://en.wikipedia.org/wiki/Wittgenstein]]
- Greatly influenced by Bertrand Russell.
- Believed that metaphysics was flawed, because it was based on the mistaken use of
  language.
*** recent nytimes discussion
[[http://nyti.ms/161XrAu]]
- traditional philosophy was inherently scientific
- purely theoretic philosophy is in conflict with a scientistic approach
- traditional philosophy over analogizes and over simplifies in the name of
  theoretical consistency
- modern philosophy must therefore avoid theory creation and should be primarily
  therapeutic
** Husserl
[[http://en.wikipedia.org/wiki/Husserl]]
- Criticized the relativism of Nietzsche, who believed that absolute truth cannot
  exist apart from our perspectives of it.
- Rejected skepticism for stating that even if there were absolute truths, we would
  have no way to know them.
- Rejected historicism for insisting that all truth is relative to the historical
  context in which it originates.
- Rejected positivism for insisting that only truths that are based on empirical
  phenomena are possible - partly because it leaves to room for mathematical
  axioms/truths which are not empirical.
- Husserl believed that philosophy should seek certainty, not facts.
* Modernity II
** Hayek
[[http://en.wikipedia.org/wiki/Friedrich_Hayek]]
- Socialism and central planning is incompatible with individual freedom
- Argued that there is a social division/dispersion of knowledge that leads to an
  efficient determination of prices.
- Prices do not necessarily represent merit.
- Therefore, rewards and social justice will not always be dispersed according to
  merit.
*** Wrote the "Road to Serfdom"
- People have incompatible preferences which central planning cannot possibly account
  for.
- Planned economies lead to concentrations of power.
- Therefore, central planning inevitably leads to a loss of freedom.
** Popper
[[http://en.wikipedia.org/wiki/Karl_Popper]]
- Was strongly influenced by how Einstein challenged the thoroughly confirmed and
  widely held confidence in Newton.
- Argued that science can strive for truth, but will never be 100% sure if/when it
  has achieved it.
- Our best form of knowledge is science, but that cannot be taken as justified truth.
- Insisted on the testability of scientific ideas.
- The objectivity of any scientific idea could only be established through critique.
** Kuhn
[[http://en.wikipedia.org/wiki/Thomas_Samuel_Kuhn]]
- The Structure of Scientific Revolutions
- Paradigm Shift
- Most scientific work is spent filling out the details of the prevailing paradigm,
  not in divergent or critical investigation.
- Over time anomalies accumulate in the prevailing paradigm, eventually building into
  a 'paradigm shift'
  - Aristotle (earth is center of universe)
  - Copernicus (sun is center of universe)
  - Newton
  - Einstein
  - ???
- A field of study is NOT a science until it has a single, unifying paradigm within
  which most of its practitioners work.
- Kuhn characterized progress in science as a highly social, and not necessarily
  rational, mechanism.
** Qine
[[http://en.wikipedia.org/wiki/Willard_Van_Orman_Quine]]
- Effective critic of logical positivism
- Attacked Empiricism
  - There is no real distinction between synthetic truths and analytic truths.
  - The principle of reductionism - that every high level statement could ultimately be reduced to simpler statements of sense experience - does not work.
  - This is because our ability to reason about sensory experience is constrained by the symbol language we use to reason about it.  These language impose their own boundary conditions to what can be reasoned.
** Habermas
[[http://en.wikipedia.org/wiki/Jürgen_Habermas]]
- Stressed the importance of the 'public sphere' of communications and how it enabled
  democracy.
- These social institutions enabled groups of individuals to discuss and openly
  debate and ultimately impact their political institutions.
*** Wrote "Theory of Communivative Action"
- Argued against the subject/object foundations of Marx and others.
- Instead, ethics and politics should be analyzed from a social perspective of
  self/other.
** Rawls
[[http://en.wikipedia.org/wiki/John_Rawls]]
*** Wrote "A Theory of Justice"
- The task of any theory of social justice is the legitimate the inequalities that
  emerge in the basic structure of society.
- To assess any system, you must do so from the 'original position'
  - Veil of Ignorance: You must not know your place in the social structure of society, or what your natural talents may be.
  - All participants must be disinterested in the outcome of the debate.
- Each person is to have an equal right to the most extensive basic liberty that is
  compatible with a similar liberty held by all others.
- If there are any inequalities in the system, they can only be justified if first -
  they are to everyone's advantage - and second - they be attached to positions or
  offices that are open to all.
** Derrida
[[http://en.wikipedia.org/wiki/Derrida]]
- Deconstructionist
- Questioned the entire western tradition of trying to define a 'true logos' behind
  our empirical view of the world.
  - This began with Plato's forms, and has been carried forward ever since.
- Follower of Nietzsche, Freud and Heidegger
  - Nietzsche did away with the concept of absolute truth.
  - Freud did away with the concept that the subjective self or consciousness has any special access to the 'logos' or true forms.
  - Heidegger did away with the notion of an 'I am' that precedes existence.
  - He argued (from Sartre) that you must exist in order to have an essence. There is no essence without existence.
- Deconstructionism directly opposes the Christian belief that Jesus/God embodies the
  perfect 'form' of man.
- Like Sartre (existentialism) - the absence of a higher plan or purpose to life does
  NOT render life meaningless.
- He wants to free us from the guilt over the absence of absolute meaning or purpose
  in life. There can be none, so get over it.
** Rorty
[[http://en.wikipedia.org/wiki/Rorty]]
- Absolute truth cannot be found in language - it is merely a statement that we
  approve of.
- Modern philosophers should give up the pursuit of absolute truth, and instead
  should seek to eliminate the cruelties of everyday life that these historical
  social norms have placed upon us.
- His basic critique of western philosophy centers on the refutation of the existence
  of a "God's eye-view" of the world
- Pragmatism is the ultimate anti-philosophy
  - Rejects the goal of defining truth as the level of correspondence with an objective reality.
  - Truth should be approached pragmatically: Does the statement work for us?
  - Also rejects absolute realism. Our experience of reality will always be influenced by the conceptual framework in which we analyze it. And that framework is constantly changing.
- Argues that many aspects of our language and are beliefs are contingent - not
  necessarily true or false.
- But it is important for our overall system of beliefs to 'hand together' and to be
  free of inconsistencies.
** Gouldner
[[http://en.wikipedia.org/wiki/Alvin_Ward_Gouldner]]
- Critic of the Marxist attempt to define society in terms of who owns the means of
  physical production, and the class distinctions that such a model result in.
- The succession of modern ideologies owes its existence to the American and French
  revolutions, which made it possible to be an intellectual dissident.
- Each ideology seeks to destroy competing ideologies while itself claiming to be
  disinterested.
- Class struggle in the modern west occur between old money and new intelligentsia
  (engineers, doctors, lawyers, scientists)
  - The struggle is not, as Marx described it, between those who controlled the means of production and the serfs below them.
** MacIntyre
[[http://en.wikipedia.org/wiki/Alasdair_MacIntyre]]
- Rejects the moral relativism that began with the Enlightenment thinkers (Locke,
  Hume, Kant).
- Admits that an absolute proof of any particular moral theory is beyond reach, but
  that our social traditions are a valid basis by which to evaluate our moral
  theories.
- Claims that social tradition is a necessary precondition for rationality. Without
  those traditions, there can be no rationality.
- The moral relativism of 'modern philosophy' is itself yet another tradition.
- He sees 'modern philosophy' as a tradition that is hostile to the very notion of
  traditions, and is thus self-contradictory.
*** The 'is-ought' gap
- This is the fundamental problem for all moral philosophy.
- If you believe in a fundamental difference between statements of fact
  vs. statements of value, it becomes impossible to to move from 'what is' to 'what
  ought to be'.
- This inability to find a rational justification to any given set of moral rules is
  a pervasive feature of modern philosophical endeavors.
- Thus modern philosophy leads to moral skepticism.
*** What is a tradition?
- The entire history of its world view over time.
- The community of people who are its bearers.
- The social practices of that community.
- They are like Kuhn's Scientific Paradigms.
- However, it must be possible for one tradition to judge other traditions based on
  rational criteria.
  - Example (Margaret Med): A primitive New Guinean tribe will have a tradition of beliefs, including truths about the world, that directly contradict most modern western traditions.
  - But we should not conclude that their belief system is un-judge-able, or equal to our traditional system of beliefs - there MUST be a basic by which to critique.
  - Nazi-ism, for example, is a tradition. We should be able to rationally argue why it is a bad tradition. Why it is wrong. Relativism would make this judgement impossible.
- The criteria: One tradition is more rational than another if
  - It can explain both the success and failures of the other tradition better than the other tradition itself can explain.
  - If it can understand the other tradition well enough to explain its failures to it in the other tradition's own terms.
** Nozick
[[http://en.wikipedia.org/wiki/Nozick]]
*** Limited Governement
- Wrote "Anarchy, State, and Utopia"
- Starts with the basic principle that a lone individual has certain rights that no
  other person may infringe upon.
- Then asks the question: With that as the basis, is there a form of government that
  can adhere to that principle? If so, what would it look like?
- The starting point is an individual who has the right to personal property. That is
  the state of nature.
  - Nozick does not attempt to justify this starting point - where does that initial right derive from and can it be proven. He simply takes it 'as-is'.
  - This is a weakness that others have used to refute much of his arguments.
- He then argues that only a very limited state may exist that would not infringe
  upon that fundamental right.
  - Involuntary redistribution of the wealth for even a single individual would be illegitimate.
- Nozick argues that a minimalist government is possible that does not infringe upon
  this basic right, and that it can be achieved without gaining the consent or
  participation of ALL individuals (which would necessarily entail some amount of
  coercion).
  - The only role of this minimal government is to enforce protection rights (police and judicial).
*** Redistribution of Wealth
- Taxes mean that others have a claim of ownership in you, and are therefore morally
  equivalent to forced labor and slavery.
- However, charitable redistribution is fine - only forced redistribution is wrong.
*** How do we assess a just society
- The means: The individual steps that led to the current distribution of wealth were
  each fair, just and entered into freely by both participants.
- The ends: The resulting distribution of wealth is equal among all participants,
  regardless of whether coercion was used to move some wealth from one to another.
* Modernity III
** Jonathan Haidt - 1963
*** The Happiness Hypothesis
- Wisdom
  - Curiosity
  - Love of learning
  - Judgement
  - Ingenuity
  - Emotional Intelligence
  - Perspective
- Courage
  - Valor
  - Persaverance
  - Integrity
- Humanity
  - Kindness
  - Loving
- Justice
  - Citizenship
  - Fairness
  - Leadership
- Termperance
  - Self-control
  - Prudence
  - Humility
- Transcendance
  - Appreciation of beauty and excellence
  - Gratitude
  - Hope
  - Spirituality
  - Foregiveness
  - Humor
  - Zest
** Jerry Fodor
[[http://en.wikipedia.org/wiki/Jerry_Fodor]]
- Proponent of psychological nativism
- mental states are relations between individuals and mental representations
- mental states are expressed in a Language of Thought
** Daniel Dennett
[[http://en.wikipedia.org/wiki/Daniel_Dennett]]
- Believes that the notions of Free Will and Determinism can be reconciled
- Focused on establishing a philosophy of mind that is firmly empirical
- Has argued that natural selection can account for the emergence of morality
** Paul Churchland
[[http://en.wikipedia.org/wiki/Paul_Churchland]]
- Proponent of Eliminative Materialism
  - [[http://en.wikipedia.org/wiki/Eliminative_materialism]]
- Every day mental concepts will eventually be eliminated by a fully mature
  neuroscience
** Thomas Nagel - 1937 -
[[http://en.wikipedia.org/wiki/Thomas_Nagel]]
- Believes that the current understanding of the physical world is insufficient to
  explain what it is like to "be some thing".
- Student of John Rawls
*** "What is it like to be a bat?"
[[http://en.wikipedia.org/wiki/What_Is_it_Like_to_Be_a_Bat%3F]]
- A refutation of reductionism as it pertains to the mind.
- Consciousness cannot be explained without reference to the phenomenon of being that
  thing.

** W.W. Bartley - 1934-1990
[[http://en.wikipedia.org/wiki/William_Warren_Bartley]]
- Close collaborator with Karl Popper
- Discussion of pancritical rationalism
  - [[http://lesswrong.com/lw/5vm/pancritical_rationalism_can_apply_to_preferences/]]
- Best known for pancritical rationalism
  - [[http://en.wikipedia.org/wiki/Pancritical_rationalism]]
  - Every possible option or explanation will have one valid criticism.
  - The goal is to choose the option whose criticism you are most willing to accept.
** Leonard Piekoff - 1933 -
[[http://en.wikipedia.org/wiki/Leonard_Peikoff]]
- Intellectual hier to Ayn Rand
- Objectivism: The Philosophy of Ayn Rand
  - [[http://en.wikipedia.org/wiki/Objectivism_(Ayn_Rand)]]
- Metaphysics
  - There is an objective reality that exists independently of our experience of it.
- Epistomology
  - All knowledge is acquired via an intellectual process
- Ethics
  - Rational self-interest
  - Rational egoism
- Economics
  - Unregulated Lassiez-faire Capitalism
- Politics
  - The role of government is to protect the rights of individuals
  - Only government should have the right to apply justice and physical punishment.
  - Democratic with guaranteed individual rights
  - Government has no rights except those delegated to it by the citizens
- Foreign Policy
  - Use of armed forces strictly defensive
  - Free trade should be encouraged
** Albert Camus - 1913-1960
[[http://en.wikipedia.org/wiki/Albert_Camus]]
- Absurdism
- We value our lives and existence
- But our mortality makes our lives meaningless
- To embrace that paradox is absurdism
** Jean-Paul Sartre - 1905-1980
[[http://en.wikipedia.org/wiki/Jean-Paul_Sartre]]
- Existentialism
- There is no creator
- We are condemned to be free
- Existence precedes essence
- Authenticity and individuality are earned, not learned
** Kurt Gödel - 1906 - 1978
[[http://en.wikipedia.org/wiki/Kurt_G%C3%B6del]]
- Best known for his "incompleteness theorems"
- For any computable axiomatic system
  - If the system is consistent, it cannot be complete
  - The consistency of the axiums cannot be proven by the system itself
** Bertrand Russell - 1872 - 1970
[[http://en.wikipedia.org/wiki/Bertrand_Russell]]
- Developed Analytic Philosophy
- Co-authored Principia Mathematica
  - [[http://en.wikipedia.org/wiki/Principia_Mathematica]]
- Established the logical underpinnings of mathematics
** Rudolf Carnap - 1891 - 1970
[[http://en.wikipedia.org/wiki/Rudolf_Carnap]]
- Member of the Vienna Circle
- Supporter of Logical Positivism
- Developed a formal version of empericism
** David J. Chalmers
*** The Hard Problem of Consciousness
[[http://consc.net/papers/facing.html]]
- Our ability to explain visual perception does not tell us what it is like to
  experience red.
- The easy problem is the explain the mechanics of how consciousness functions.
- The hard problem: there is something it is like to be a conscious organism.
- What makes up consciousness? Everything that we can report back on verbally.
